name: Appium CICD trying

on:
  workflow_dispatch:

jobs:
  run_my_first_test:
    runs-on: ubuntu-latest

    steps:
    - name: pull the code first
      uses: actions/checkout@v3

    - name: install appium 
      run: |
       echo "Appium install started msg"
       npm install -g appium@1.18.3
       appium -v
       appium &>/dev/null &
       echo "appium after msg"

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: open Android Emulator 
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: mvn clean test -Papptest

    - name: reporting
      uses: actions/upload-artifact@v2
      with:
          name: test-reports
          path: target/surefire-reports/emailable-report.html
          retention-days: 5
