name: Appium CICD trying

on:
  workflow_dispatch:

jobs:
  run_my_first_test:
    runs-on: macos-latest

    steps:
    - name: pull the code first
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven      

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: setup Android root
      run: sdkmanager "system-images;android-28;default;x86_64"

    - name: install appium 
      run: |
       echo "Appium install started msg"
       npm install -g appium@v1.22
       appium -v
       appium &>/dev/null &
       echo "appium after msg"

    - name: open Android Emulator 
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        script: |
          adb devices
          echo "Will start running appium Tests"
          adb shell pm list packages
          mvn clean test -Papptest
      
    - name: reporting
      uses: actions/upload-artifact@v2
      with:
          name: test-reports
          path: target/surefire-reports/emailable-report.html
          retention-days: 5
