name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  run_my_first_test:
    runs-on: ubuntu-latest

    steps:
    - name: pull the code first
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean test -Pcdtest

    - name: reporting
      uses: actions/upload-artifact@v2
      with:
          name: test-reports
          path: target/surefire-reports/emailable-report.html
          retention-days: 5
